version: '3.7'

services:

  web:
    container_name: node
    build: .
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/app

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/mongo_configdb:/data/configdb
      - ~/mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ruanqiaohua
      MONGO_INITDB_ROOT_PASSWORD: 62203957
